export const BASE_SET_SITE_MAP = 'BASE_SET_SITE_MAP'
export const BASE_ACTION_NO_STATE = 'BASE_ACTION_NO_STATE'

//
export const SET_CURRENT_ALBUMS = 'SET_CURRENT_ALBUMS'
export const GET_ALBUMS_MUSICS = 'GET_ALBUMS_MUSICS'
export const SET_CURRENT_MUSIC = 'SET_CURRENT_MUSIC'
export const SET_CURRENT_MUSIC_URL = 'SET_CURRENT_MUSIC_URL'

//
export const GET_BANNERS = 'GET_BANNERS'

// RADIO
export const GET_RADIO_CATEGORIES = 'GET_RADIO_CATEGORIES'
